# Generated by Django 6.1 on 2026-08-26 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='productvariants',
            unique_together={('product', 'color', 'size')},
        ),
    ]
