# Generated by Django 6.1 on 2026-08-27 02:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_productvariants_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variantimage',
            name='variant',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='products.productvariants'),
        ),
    ]
