# Generated by Django 6.1 on 2026-08-27 18:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_variantimage_variant'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productvariants',
            name='price',
        ),
        migrations.AddField(
            model_name='product',
            name='price',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='variantimage',
            name='variant',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='image', to='products.productvariants'),
        ),
    ]
