# Generated by Django 6.1 on 2026-08-27 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_remove_productvariants_price_product_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvariants',
            name='image',
            field=models.ImageField(default='', upload_to='products/'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='VariantImage',
        ),
    ]
