# Generated by Django 6.1 on 2026-08-27 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_productvariants_image_delete_variantimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvariants',
            name='quantity',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
    ]
