# Generated by Django 6.1 on 2026-08-28 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='productvariants',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
    ]
