# Generated by Django 6.1 on 2026-10-02 12:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_product_discount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
    ]
